parameters:
    media.type.class: 'MediaBundle\Form\Type\MediaType'
    media.type.manager: 'MediaBundle\Manager\MediaManager'
    media.data.transformer.class: 'MediaBundle\Form\DataTransformer\MediaDataTransformer'
    
services:
    
    media.form.type.media:
        class: %media.type.class%
        arguments: 
            - "@media.form.manager.service"
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }
            
    media.form.manager.service:
        class: %media.type.manager%
        arguments:
            - "@doctrine.orm.entity_manager"
            - "%kernel.root_dir%"
            - "%media.upload_path%"
            
    media.data.transformer.service:
        class: %media.data.transformer.class%
        arguments: 
            - "@media.form.manager.service"

    media.twig_extension:
        class: MediaBundle\Twig\MediaExtension
        arguments:
            - '@request_stack'
            - '%media.upload_path%'
        tags:
            - { name: twig.extension }
